### ISSUE TITLE
ROI compare % is very different then ICONOMI API

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [ICNHodler/CryptoCharts#13]
For 6 months. CARUS-AR ROI (according to ICONOMI API) is **+56.61%**
But the chart generated by CryptoCharts shows **+33.61%** when I set code for 183 days..

When I test 7 days, CryptoCharts roiComparison gives: **+10.89%**
ICONOMI API: **+11.97%**

Code used:

```
CryptoCharts.roiComparison({
    chart_id: "mychart",
    cryptocompare_tickers: ["BTC","ETH"],
    iconomi_tickers: ["CAR"],
    last_days: 183,
    axes: true,
    options: {
      title: {
        text: undefined
      },
      tooltip: {
        enabled: true
      },
      legend: {
        show: false
      },
      colors: ['#229ad5','#137603','#c99c00'],
      chart:{
        events: {
          mounted: function(chartContext, config) {
            removeFadeOut(document.querySelectorAll("#mychart .loading")[0], 500);
            function removeFadeOut( el, speed ) {
              var seconds = speed/1000;
              el.style.transition = "opacity "+seconds+"s ease";
              el.style.opacity = 0;
              setTimeout(function() {
                el.parentNode.removeChild(el);
              }, speed);
            }
          }
        }
      }
    }
  });
```

**Comment by jesusthatsgreat** [comment]
Fixed in latest update: https://github.com/ICNHodler/CryptoCharts/releases/tag/v1.1.1

Fixed by fetching latest price from ICONOMI and using it to replace the last datapoint in the daily prices. Also confirmed with ICONOMI that 1 month = 30 days, so 6m = 180 days and so on. ROI figures over time are now almost identical to ICONOMI's API results.
